// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function GetAPIPort() {
  return window['go']['main']['App']['GetAPIPort']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetStreamURL(arg1) {
  return window['go']['main']['App']['GetStreamURL'](arg1);
}

export function GetThumbnailURL(arg1) {
  return window['go']['main']['App']['GetThumbnailURL'](arg1);
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function RebuildIndex(arg1) {
  return window['go']['main']['App']['RebuildIndex'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SendAuthCode(arg1) {
  return window['go']['main']['App']['SendAuthCode'](arg1);
}

export function SyncFolders() {
  return window['go']['main']['App']['SyncFolders']();
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}

export function UploadFilePath(arg1, arg2) {
  return window['go']['main']['App']['UploadFilePath'](arg1, arg2);
}

export function VerifyAuthCode(arg1) {
  return window['go']['main']['App']['VerifyAuthCode'](arg1);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
