// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {telegram} from '../models';

export function CreateFolder(arg1:string):Promise<storage.Folder>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function GetAPIPort():Promise<number>;

export function GetAuthStatus():Promise<telegram.AuthStatus>;

export function GetFiles(arg1:string):Promise<Array<storage.File>>;

export function GetFolders():Promise<Array<storage.Folder>>;

export function GetStreamURL(arg1:string):Promise<string>;

export function GetThumbnailURL(arg1:string):Promise<string>;

export function IsConfigured():Promise<boolean>;

export function RebuildIndex(arg1:string):Promise<number>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:number,arg2:string):Promise<void>;

export function SendAuthCode(arg1:string):Promise<void>;

export function SyncFolders():Promise<Array<storage.Folder>>;

export function UploadFile(arg1:string):Promise<storage.File>;

export function UploadFilePath(arg1:string,arg2:string):Promise<storage.File>;

export function VerifyAuthCode(arg1:string):Promise<void>;

export function VerifyPassword(arg1:string):Promise<void>;
