// Wails binding wrappers
// These functions call Go methods bound via Wails

import {
  GetAuthStatus,
  SendAuthCode,
  VerifyAuthCode,
  VerifyPassword,
  GetFolders,
  CreateFolder,
  RenameFolder,
  DeleteFolder,
  ToggleFolderHidden,
  GetFiles,
  UploadFile,
  UploadFiles,
  UploadFilePath,
  DownloadFileTo,
  DownloadFilesTo,
  DeleteFile,
  RenameFile,
  GetStreamURL,
  GetThumbnailURL,
  GetDownloadURL,
  OpenPlayer,
  RebuildIndex,
  SyncFolders,
  GetAPIPort,
  IsConfigured,
  SaveConfig,
} from '../../wailsjs/go/main/App';

export {
  GetAuthStatus,
  SendAuthCode,
  VerifyAuthCode,
  VerifyPassword,
  GetFolders,
  CreateFolder,
  RenameFolder,
  DeleteFolder,
  ToggleFolderHidden,
  GetFiles,
  UploadFile,
  UploadFiles,
  UploadFilePath,
  DownloadFileTo,
  DownloadFilesTo,
  DeleteFile,
  RenameFile,
  GetStreamURL,
  GetThumbnailURL,
  GetDownloadURL,
  OpenPlayer,
  RebuildIndex,
  SyncFolders,
  GetAPIPort,
  IsConfigured,
  SaveConfig,
};
